# Generated by Django 4.0.2 on 2022-06-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0003_quesmodel1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quesmodel1',
            old_name='platform_name',
            new_name='platformnames',
        ),
    ]
