# Generated by Django 4.0.2 on 2022-06-20 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0004_rename_platform_name_quesmodel1_platformnames'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuesModel1',
        ),
        migrations.DeleteModel(
            name='Questionanswer',
        ),
    ]
