# Generated by Django 4.0.2 on 2022-06-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0005_delete_quesmodel1_delete_questionanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='', max_length=200)),
                ('q1', models.CharField(max_length=300)),
                ('a1', models.CharField(max_length=300)),
            ],
        ),
    ]
